// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: GodQQ/CloudStore/protocol/protocol.proto

package gRPCProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FilesInfo_GetUploadingFileList_FullMethodName = "/FilesInfo/GetUploadingFileList"
	FilesInfo_RequestUploadFile_FullMethodName    = "/FilesInfo/RequestUploadFile"
	FilesInfo_RequestDownloadFile_FullMethodName  = "/FilesInfo/RequestDownloadFile"
	FilesInfo_UploadFileComplete_FullMethodName   = "/FilesInfo/UploadFileComplete"
)

// FilesInfoClient is the client API for FilesInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilesInfoClient interface {
	// 请求获得文件的上传列表
	GetUploadingFileList(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*FileList, error)
	// 请求建立一个传输请求
	RequestUploadFile(ctx context.Context, in *UploadFileInfo, opts ...grpc.CallOption) (*UploadFileInfoRsp, error)
	// 请求建立一个下载的请求
	RequestDownloadFile(ctx context.Context, in *DownloadFileInfo, opts ...grpc.CallOption) (*DownloadFileInfoRsp, error)
	// 确认完成上传文件
	UploadFileComplete(ctx context.Context, in *CompleteInfo, opts ...grpc.CallOption) (*Empty, error)
}

type filesInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewFilesInfoClient(cc grpc.ClientConnInterface) FilesInfoClient {
	return &filesInfoClient{cc}
}

func (c *filesInfoClient) GetUploadingFileList(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*FileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileList)
	err := c.cc.Invoke(ctx, FilesInfo_GetUploadingFileList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesInfoClient) RequestUploadFile(ctx context.Context, in *UploadFileInfo, opts ...grpc.CallOption) (*UploadFileInfoRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileInfoRsp)
	err := c.cc.Invoke(ctx, FilesInfo_RequestUploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesInfoClient) RequestDownloadFile(ctx context.Context, in *DownloadFileInfo, opts ...grpc.CallOption) (*DownloadFileInfoRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadFileInfoRsp)
	err := c.cc.Invoke(ctx, FilesInfo_RequestDownloadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesInfoClient) UploadFileComplete(ctx context.Context, in *CompleteInfo, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, FilesInfo_UploadFileComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilesInfoServer is the server API for FilesInfo service.
// All implementations must embed UnimplementedFilesInfoServer
// for forward compatibility.
type FilesInfoServer interface {
	// 请求获得文件的上传列表
	GetUploadingFileList(context.Context, *UserInfo) (*FileList, error)
	// 请求建立一个传输请求
	RequestUploadFile(context.Context, *UploadFileInfo) (*UploadFileInfoRsp, error)
	// 请求建立一个下载的请求
	RequestDownloadFile(context.Context, *DownloadFileInfo) (*DownloadFileInfoRsp, error)
	// 确认完成上传文件
	UploadFileComplete(context.Context, *CompleteInfo) (*Empty, error)
	mustEmbedUnimplementedFilesInfoServer()
}

// UnimplementedFilesInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFilesInfoServer struct{}

func (UnimplementedFilesInfoServer) GetUploadingFileList(context.Context, *UserInfo) (*FileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadingFileList not implemented")
}
func (UnimplementedFilesInfoServer) RequestUploadFile(context.Context, *UploadFileInfo) (*UploadFileInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestUploadFile not implemented")
}
func (UnimplementedFilesInfoServer) RequestDownloadFile(context.Context, *DownloadFileInfo) (*DownloadFileInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDownloadFile not implemented")
}
func (UnimplementedFilesInfoServer) UploadFileComplete(context.Context, *CompleteInfo) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFileComplete not implemented")
}
func (UnimplementedFilesInfoServer) mustEmbedUnimplementedFilesInfoServer() {}
func (UnimplementedFilesInfoServer) testEmbeddedByValue()                   {}

// UnsafeFilesInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilesInfoServer will
// result in compilation errors.
type UnsafeFilesInfoServer interface {
	mustEmbedUnimplementedFilesInfoServer()
}

func RegisterFilesInfoServer(s grpc.ServiceRegistrar, srv FilesInfoServer) {
	// If the following call pancis, it indicates UnimplementedFilesInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FilesInfo_ServiceDesc, srv)
}

func _FilesInfo_GetUploadingFileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesInfoServer).GetUploadingFileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesInfo_GetUploadingFileList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesInfoServer).GetUploadingFileList(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesInfo_RequestUploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesInfoServer).RequestUploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesInfo_RequestUploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesInfoServer).RequestUploadFile(ctx, req.(*UploadFileInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesInfo_RequestDownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadFileInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesInfoServer).RequestDownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesInfo_RequestDownloadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesInfoServer).RequestDownloadFile(ctx, req.(*DownloadFileInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesInfo_UploadFileComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesInfoServer).UploadFileComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesInfo_UploadFileComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesInfoServer).UploadFileComplete(ctx, req.(*CompleteInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// FilesInfo_ServiceDesc is the grpc.ServiceDesc for FilesInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilesInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FilesInfo",
	HandlerType: (*FilesInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUploadingFileList",
			Handler:    _FilesInfo_GetUploadingFileList_Handler,
		},
		{
			MethodName: "RequestUploadFile",
			Handler:    _FilesInfo_RequestUploadFile_Handler,
		},
		{
			MethodName: "RequestDownloadFile",
			Handler:    _FilesInfo_RequestDownloadFile_Handler,
		},
		{
			MethodName: "UploadFileComplete",
			Handler:    _FilesInfo_UploadFileComplete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "GodQQ/CloudStore/protocol/protocol.proto",
}
